[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "s2zmrr2SqcwCdeAGRiPFftDSV9CRhXqAbRcMgmh4goC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
